version: "3.5"

services:

    nginx_rnamining:
        build: ./build/nginx
        container_name: rnamining_webserver
        volumes:
            - ./volumes/rnamining-front:${DOCUMENT_ROOT}
        depends_on:
            - php_rnamining
        networks:
            - gatewayapps_proxy
            - php
        restart: always

    php_rnamining:
        build: ./build/php
        container_name: rnamining_php
        volumes:
            - ./volumes/rnamining-front:${DOCUMENT_ROOT}
        networks:
             - php
        #environment:
        #     - REPOSITORY=${REPOSITORY}
         #    - BRANCH_STABLE=${BRANCH_STABLE}
          #   - TOKEN=${TOKEN}
        restart: always

networks:
    php:
