version: "3.5"

services:

    monitor_traefik:
        image: traefik:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./volumes/traefik/traefik.toml:/traefik.toml
            - ./volumes/traefik/acme.json:/acme.json
        labels:
            - "traefik.enable=false"
            - "traefik.docker.network=proxy"
        networks:
            - proxy
        command: "--docker"

    nginx_rnamining:
        build: ./build/nginx
        container_name: rnamining_webserver
        volumes:
            - ./volumes/rnamining-front:${DOCUMENT_ROOT}
        labels:
            - "traefik.port=80"
            - "traefik.docker.network=proxy"
            - "traefik.frontend.rule=Host:${FQDN}"
        depends_on:
            - php_rnamining
        networks:
            - proxy
        restart: always

    php_rnamining:
        build: ./build/php
        container_name: rnamining_php
        volumes:
            - ./volumes/rnamining-front:${DOCUMENT_ROOT}
        labels:
            - "traefik.enable=false"
        depends_on:
            - monitor_traefik
        networks:
             - proxy
        restart: always

networks:
    proxy:
